"""add verification_reason to users

Revision ID: 158dcc6ecbf6
Revises: 
Create Date: 2026-06-03 13:07:29.856949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '158dcc6ecbf6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seller_user_id'))

    op.drop_table('seller')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_reason', sa.Text(), nullable=True))
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('district')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_email_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('verification_reason')

    op.create_table('seller',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vehicle_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('license_number', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('selfie_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('national_id_front_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('national_id_back_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('seller_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('seller_pkey')),
    sa.UniqueConstraint('email', name=op.f('seller_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('license_number', name=op.f('seller_license_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('seller', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seller_user_id'), ['user_id'], unique=True)

    # ### end Alembic commands ###
