"""add payment tables and fix listing_interest columns

Revision ID: bf93b60e3852
Revises: 158dcc6ecbf6
Create Date: 2026-06-05 14:38:39.740030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf93b60e3852'
down_revision = '158dcc6ecbf6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('listing_interests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('listing_title', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('seller_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('seller_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pickup_photo_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE listing_interests SET updated_at = created_at WHERE updated_at IS NULL")

    with op.batch_alter_table('listing_interests', schema=None) as batch_op:
        batch_op.alter_column('updated_at', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listing_interests', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('pickup_photo_url')
        batch_op.drop_column('seller_name')
        batch_op.drop_column('seller_phone')
        batch_op.drop_column('listing_title')

    # ### end Alembic commands ###
